name: Lab 1

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    types:
      - edited
      - opened
      - labeled
      - unlabeled
      - synchronize
      - reopened
    branches:
      - '*'

jobs:
  issuenumber-job:
    runs-on: ubuntu-latest
    name: Check Commit Messages

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 9
        submodules: false

    - uses: actions/cache@v1
      id: depcache
      with:
        path: deps
        key: requirements-pip-${{ hashFiles('requirements.txt') }}

    - name: Download dependencies
      if: steps.depcache.outputs.cache-hit != 'true'
      run: |
        pip download --dest=deps -r requirements.txt

    - name: Install Python deps
      run: |
        pip install -U --no-index --find-links=deps deps/*

    - name: Run tests
      run: |
        pytest

    - uses: RobertoPrevato/GitHubActionLabTS1@release/v1
      id: example
      with:
        milliseconds: 1000
        myToken: ${{ secrets.GITHUB_TOKEN }}
#    - name: Check output
#      run: "echo \"Last issue number is ${{ steps.issuenumber.outputs.issuenumber }}\""
