name: Lab 1

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - '*'

jobs:
  issuenumber-job:
    runs-on: ubuntu-latest
    name: Check Commit Messages

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 9
        submodules: false
    - uses: RobertoPrevato/GitHubActionLabTS1@release/v1
      id: example
      with:
        milliseconds: 1000
        myToken: ${{ secrets.GITHUB_TOKEN }}
#    - name: Check output
#      run: "echo \"Last issue number is ${{ steps.issuenumber.outputs.issuenumber }}\""
